CREATE TABLE `t_user` (
	`id` INT(120) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT '用户唯一标识',
	`name` VARCHAR(180) NULL DEFAULT NULL COMMENT '用户真是姓名',
	`card_id` VARCHAR(140) NULL DEFAULT NULL COMMENT '用户身份证号码',
	`cellphone` VARCHAR(50) NULL DEFAULT NULL COMMENT '手机号码',
	`telephone` VARCHAR(50) NULL DEFAULT NULL COMMENT '固定电话号码',
	`email` VARCHAR(240) NULL DEFAULT NULL COMMENT '邮政编码'
)
COMMENT='用户详细信息表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
